version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-container
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - mynetwork

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube-container
    ports:
      - "9000:9000"
    networks:
      - mynetwork

volumes:
  jenkins-data:

networks:
  mynetwork:
